Fix `git llvm` script when no arguments are supplied on Python 3
Instead of displaying a help message, it was issuing an error message:

  AttributeError: 'Namespace' object has no attribute 'func'

https://bugs.python.org/issue16308 has more information on the bug.

git-svn-id: http://llvm.org/svn/llvm-project/llvm/trunk@367320 91177308-0d34-0410-b5e6-96231b3b80d8