Remove unused variable introduced in r332336
The unused variable caused a compilation warning:

../lib/Target/X86/X86ISelLowering.cpp:34614:17: error: unused variable 'SMax' [-Werror,-Wunused-variable]
    if (SDValue SMax = MatchMinMax(SMin, ISD::SMAX, C1))
                ^
1 error generated.

git-svn-id: http://llvm.org/svn/llvm-project/llvm/trunk@332431 91177308-0d34-0410-b5e6-96231b3b80d8